// Textos de la interfaz de Janulus (no del contenido pedagógico, ese vive en
// matrixData.js) — lookup local a este juego, igual que voicePrefs.js, sin
// tocar el sistema de i18n global: son ~70 strings específicas de este
// componente, no texto de la plataforma en general.
const STRINGS = {
  es: {
    estructura: 'Estructura', verbo: 'Verbo', objeto: 'Objeto',
    vel: 'Vel.',
    mapa: '← Mapa',
    pts: 'pts',
    leerVoz: '🔊 Leer en voz alta',
    escribeTocaPalabras: 'Escribe o toca las palabras…',
    frase: 'Frase:',
    conversacionPractica: '🗨️ Conversación de práctica',
    verPuntuacion: 'Ver mi puntuación 🏆',
    siguiente: 'Siguiente →',
    tecnicaJanulus: 'Técnica Janulus',
    leerIntro: '🔊 Leer introducción',
    vamos: '¡Vamos! →',
    accionVerbo: 'Acción (verbo)',
    comoLlamaAccion: '¿Cómo se llama esta acción?',
    comoLlamaObjeto: '¿Cómo se llama este objeto?',
    definicion: 'Definición',
    ejemplos: 'Ejemplos',
    etimologia: 'Etimología',
    correcto: '✅ ¡Correcto!',
    intentaloDeNuevo: '❌ Inténtalo de nuevo',
    escribePalabra: 'Escribe la palabra…',
    pista: 'Pista',
    mas: 'Más',
    escuchar: '🔊 Escuchar',
    saltar: 'Saltar →',
    continuar: 'Continuar →',
    construyeOracion: 'Construye la oración completa',
    escribirMode: '✍️ Escribir',
    bloquesMode: '🧩 Bloques',
    escribeFraseCompleta: 'Escribe la frase completa…',
    perfecto: '✅ ¡Perfecto!',
    pistaEscuchar: 'Pista (escuchar)',
    revelarPalabra: 'Revelar palabra',
    ordenIncorrecto: '❌ Orden incorrecto',
    ordenLabel: 'Orden:',
    pistaGato: '🐱 Pista',
    hintBubble1: 'Escucha la frase despacio. 🔊 El oído reconoce el orden antes que la mente.',
    hintBubble2: (base) => `La frase empieza con "${base}"… ¿qué va después?`,
    fraseEmpieza: (base) => `La frase empieza con ${base}`,
    flag: '🇪🇸',
    tagline: 'Aprende idiomas ensamblando bloques de frases completas.',
    jugar: 'Jugar →',
    oliverGuia: '🐱 Oliver te guiará con pistas',
    eligeIdioma: 'Elige tu idioma',
    nivelCompletado: '¡Nivel completado!',
    puntuacion: 'Puntuación:',
    efectividad: 'de efectividad',
    repetir: '↺ Repetir',
    powellFooter: '🐱 Powell Janulus dominaba 42 idiomas. ¡Tú vas por buen camino!',
    idiomasBack: '← Idiomas',
    mapaNiveles: 'Mapa de Niveles',
    historia: '📜 Historia',
  },
  en: {
    estructura: 'Structure', verbo: 'Verb', objeto: 'Object',
    vel: 'Speed',
    mapa: '← Map',
    pts: 'pts',
    leerVoz: '🔊 Read aloud',
    escribeTocaPalabras: 'Type or tap the words…',
    frase: 'Sentence:',
    conversacionPractica: '🗨️ Practice conversation',
    verPuntuacion: 'See my score 🏆',
    siguiente: 'Next →',
    tecnicaJanulus: 'Janulus Technique',
    leerIntro: '🔊 Read introduction',
    vamos: "Let's go! →",
    accionVerbo: 'Action (verb)',
    comoLlamaAccion: 'What is this action called?',
    comoLlamaObjeto: 'What is this object called?',
    definicion: 'Definition',
    ejemplos: 'Examples',
    etimologia: 'Etymology',
    correcto: '✅ Correct!',
    intentaloDeNuevo: '❌ Try again',
    escribePalabra: 'Type the word…',
    pista: 'Hint',
    mas: 'More',
    escuchar: '🔊 Listen',
    saltar: 'Skip →',
    continuar: 'Continue →',
    construyeOracion: 'Build the full sentence',
    escribirMode: '✍️ Type',
    bloquesMode: '🧩 Blocks',
    escribeFraseCompleta: 'Type the full sentence…',
    perfecto: '✅ Perfect!',
    pistaEscuchar: 'Hint (listen)',
    revelarPalabra: 'Reveal word',
    ordenIncorrecto: '❌ Wrong order',
    ordenLabel: 'Order:',
    pistaGato: '🐱 Hint',
    hintBubble1: 'Listen to the sentence slowly. 🔊 Your ear picks up the order before your mind does.',
    hintBubble2: (base) => `The sentence starts with "${base}"… what comes next?`,
    fraseEmpieza: (base) => `The sentence starts with ${base}`,
    flag: '🇬🇧',
    tagline: 'Learn languages by assembling complete sentence blocks.',
    jugar: 'Play →',
    oliverGuia: '🐱 Oliver will guide you with hints',
    eligeIdioma: 'Choose your language',
    nivelCompletado: 'Level complete!',
    puntuacion: 'Score:',
    efectividad: 'accuracy',
    repetir: '↺ Retry',
    powellFooter: "🐱 Powell Janulus mastered 42 languages. You're on your way!",
    idiomasBack: '← Languages',
    mapaNiveles: 'Level Map',
    historia: '📜 History',
  },
}

export function strings(uiLang) {
  return STRINGS[uiLang] ?? STRINGS.es
}
